# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bcinterp', [dirname(__file__)])
        except ImportError:
            import _bcinterp
            return _bcinterp
        if fp is not None:
            try:
                _mod = imp.load_module('_bcinterp', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bcinterp = swig_import_helper()
    del swig_import_helper
else:
    import _bcinterp
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Bcinterp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Bcinterp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Bcinterp, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dim_xa"] = _bcinterp.Bcinterp_dim_xa_set
    __swig_getmethods__["dim_xa"] = _bcinterp.Bcinterp_dim_xa_get
    if _newclass:dim_xa = _swig_property(_bcinterp.Bcinterp_dim_xa_get, _bcinterp.Bcinterp_dim_xa_set)
    __swig_setmethods__["dim_ya"] = _bcinterp.Bcinterp_dim_ya_set
    __swig_getmethods__["dim_ya"] = _bcinterp.Bcinterp_dim_ya_get
    if _newclass:dim_ya = _swig_property(_bcinterp.Bcinterp_dim_ya_get, _bcinterp.Bcinterp_dim_ya_set)
    __swig_setmethods__["dim_za"] = _bcinterp.Bcinterp_dim_za_set
    __swig_getmethods__["dim_za"] = _bcinterp.Bcinterp_dim_za_get
    if _newclass:dim_za = _swig_property(_bcinterp.Bcinterp_dim_za_get, _bcinterp.Bcinterp_dim_za_set)
    __swig_setmethods__["xa"] = _bcinterp.Bcinterp_xa_set
    __swig_getmethods__["xa"] = _bcinterp.Bcinterp_xa_get
    if _newclass:xa = _swig_property(_bcinterp.Bcinterp_xa_get, _bcinterp.Bcinterp_xa_set)
    __swig_setmethods__["ya"] = _bcinterp.Bcinterp_ya_set
    __swig_getmethods__["ya"] = _bcinterp.Bcinterp_ya_get
    if _newclass:ya = _swig_property(_bcinterp.Bcinterp_ya_get, _bcinterp.Bcinterp_ya_set)
    __swig_setmethods__["za"] = _bcinterp.Bcinterp_za_set
    __swig_getmethods__["za"] = _bcinterp.Bcinterp_za_get
    if _newclass:za = _swig_property(_bcinterp.Bcinterp_za_get, _bcinterp.Bcinterp_za_set)
    def __init__(self, *args): 
        this = _bcinterp.new_Bcinterp(*args)
        try: self.this.append(this)
        except: self.this = this
    def evaluate_point(self, *args): return _bcinterp.Bcinterp_evaluate_point(self, *args)
    def evaluate_array(self, *args): return _bcinterp.Bcinterp_evaluate_array(self, *args)
    __swig_destroy__ = _bcinterp.delete_Bcinterp
    __del__ = lambda self : None;
Bcinterp_swigregister = _bcinterp.Bcinterp_swigregister
Bcinterp_swigregister(Bcinterp)



