language: python
python:
  - 2.6
  - 2.7
before_install:
  - pip install numpy --use-mirrors -qq
  - pip install nose --use-mirrors  -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install numexpr --use-mirrors -qq
  - pip install cython --use-mirrors -qq
  - pip install tables --use-mirrors -qq
  - pip install scipy --use-mirrors -qq
install:
  - python setup.py -q install
script:
  - nosetests
