language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev 
  - pip install --use-mirrors -qq numexpr
  - sudo apt-get update
  - sudo apt-get install -qq python-numpy 
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-matplotlib
  - sudo apt-get install -qq swig
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install --use-mirrors -qq nose
  - pip install --use-mirrors -qq cython
  - pip install --use-mirrors -qq tables
  - pip install git+git://github.com/rmcgibbo/mdtraj.git
  - svn co https://fable.svn.sourceforge.net/svnroot/fable/fabio/branches/v0.1.0 fabio; cd fabio; python setup.py install; cd ..
install:
  - python setup.py install --no-openmp
script:
  - nosetests -v
