#!/usr/bin/env python

"""
Convert crystallographic binary files (.cbf) to an ODIN shotset file.
"""

import os
from glob import glob

from odin.utils import odinparser
from odin.xray import Shotset
from odin.parse import CBF

def main(input_fn, output_fn):
    
    if os.path.isdir(input_fn):
        print "Locating CBF files in dir: %s" % input_fn
        cbf_files = glob( os.path.join( input_fn, '*.cbf' ) )
        print "Found %d CBF files" % len(cbf_files)
        shotset = CBF.files_to_shotset(cbf_files, shotset_filename=output_fn)
        
    else: # is file
        print "Loading single file: %s" % input_fn
        c = CBF(input_fn)
        s = c.as_shotset()
        s.save(output_fn)
        print "Saved: %s" % output_fn
    
    return
    
    
if __name__ == '__main__':
    
    parser = odinparser('''Convert crystallographic binary files (.cbf) to an 
ODIN shotset file (.shot). Files should share a common detector geometry and 
mask, and differ only in intensity.''')
    
    parser.add_argument('input', type=str, 
                        help='''Either a single CBF file, or a directory 
                                containing one or more CBF files.''')
    parser.add_argument('-o', '--output', default='shotset.shot',
                        help='The output file name. Default: shotset.shot')

    args = parser.parse_args()

    main(args.input, args.output)
