#!/usr/bin/env python

"""
Plot a sequential series of intensity profiles.
"""

from odin import xray
from odin.utils import odinparser

import numpy as np
import matplotlib.pyplot as plt


def main(shotset_fn, num_shots):
    
    ss = xray.Shotset.load(shotset_fn)
    
    fig = plt.figure()
    
    offset = 0.0
    
    for i in range(num_shots):
        ip = ss[i].intensity_profile()
        plt.plot(ip[:,0], ip[:,1] + offset, lw=2, color='b')
        offset += ip[:,1].max()
        
    plt.xlabel(r'q / $\AA^{-1}$')
    plt.ylabel('Intensity')
    
    plt.show()
    
    return


if __name__ == '__main__':
	
    parser = odinparser('Plot a sequential series of intensity profiles.')

    parser.add_argument('-s', '--shotset',
                        help='An ODIN shot file to plot')
    parser.add_argument('-n', '--numshots', type=int, default=5,
                        help='The number of shots to plot. Default: 5.')
                        
    args = parser.parse_args()
    
    main(args.shotset, args.numshots)
