#!/usr/bin/env python

"""
Convert kitty-outputted HDF5 files to odin ShotSets
"""

from odin import parse
from odin.utils import odinparser

def main(yaml_fn, max_shots, mode, output_fn):
    
    ks = parse.KittyH5(yaml_fn, mode=mode)
    ss = ks.convert(max_shot_limit=max_shots)
    
    print "Saved: %s" % output_fn
    ss.save(output_fn)
    
    return


if __name__ == '__main__':
	
    parser = odinparser('Convert kitty-outputted HDF5 files to odin ShotSets')

    parser.add_argument('-y', '--yaml',
                        help='Kitty generated YAML decriptor file.')
    parser.add_argument('-n', '--nmaxshots', default=None,
                        help='The maximum number of shots to convert. Default: All.')
    parser.add_argument('-m', '--mode', default='asm',
                        help='Mode to run in: {"asm", "raw"}. Default: "asm".')                    
    parser.add_argument('-o', '--output', default='shotset.shot',
                        help='''A Shotset object, written to disk in h5 format. Default: shotset.shot''')
                        
    args = parser.parse_args()
    
    main(args.yaml, args.nmaxshots, args.mode, args.output)