#!/usr/bin/env python

"""
Plot a sequential series of rings at a specific q-value.
"""

from odin import xray
from odin.utils import odinparser

import numpy as np
import matplotlib.pyplot as plt


def main(shotset_fn, qvalues, num_shots):
    
    ss = xray.ShotSet.load(shotset_fn)
    
    fig = plt.figure()
    
    offset = 0.0
    
    for i in range(num_shots):
        phis = ss[i].phi_values
        ir = ss[i].I_ring(q_value)
        plt.plot(phis, ir + offset, lw=2, color='b')
        offset += ip[:,1].max()
        
    plt.x_label(r'$\phi$ / Degrees')
    plt.y_label('Intensity')
    
    plt.show()
    
    return


if __name__ == '__main__':
	
    parser = odinparser('Plot a sequential series of rings at a specific q-value.')

    parser.add_argument('-s', '--shotset',
                        help='An ODIN shot file to plot')
    parser.add_argument('-q', '--qvalue', type=float,
                        help='The q-value to plot the ring at.')
    parser.add_argument('-n', '--numshots', type=int, default=5,
                        help='The number of shots to plot. Default: 5.')
                        
    args = parser.parse_args()
    
    main(args.shotset, args.qvalue, args.numshots)