#!/usr/bin/env python

"""
Display a shot in polar coordinates
"""

from odin import xray
from odin.utils import odinparser

import numpy as np
import matplotlib.pyplot as plt


def main(shotset_fn, qvalues, num_shots):
    
    ss = xray.ShotSet.load(shotset_fn)
    s = ss[0]
    
    fig = plt.figure()
    
    polar_i = s.polar_intensities.reshape(s.num_q, s.num_phi)

    plt.x_label(r'$\phi$ / Degrees')
    plt.y_label(r'q / $\AA^{-1}$')
    
    plt.show()
    
    return


if __name__ == '__main__':
	
    parser = odinparser('Plot a sequential series of rings at a specific q-value.')

    parser.add_argument('-s', '--shotset',
                        help='An ODIN shot file to plot')
    parser.add_argument('-q', '--qvalue', type=float,
                        help='The q-value to plot the ring at.')
    parser.add_argument('-n', '--numshots', type=int, default=5,
                        help='The number of shots to plot. Default: 5.')
                        
    args = parser.parse_args()
    
    main(args.shotset, args.qvalue, args.numshots)