#!/usr/bin/env python

"""
Display a shot in polar coordinates
"""

from odin import xray
from odin.utils import odinparser

import numpy as np
import matplotlib.pyplot as plt


def main(shotset_fn):
    
    ss = xray.Shotset.load(shotset_fn)
    s = ss[0]
    
    fig = plt.figure()
    
    polar_i = s.polar_intensities.reshape(s.num_phi, s.num_q)
    plt.imshow(polar_i)

    plt.xlabel(r'$\phi$ / Degrees')
    plt.ylabel(r'q / $\AA^{-1}$')
    
    plt.show()
    
    return


if __name__ == '__main__':
	
    parser = odinparser('Plot a sequential series of rings at a specific q-value.')

    parser.add_argument('-s', '--shotset',
                        help='An ODIN shot file to plot')
                        
    args = parser.parse_args()
    
    main(args.shotset)
