#!/usr/bin/env python

"""
Plot the intensity profile of a shot or shotset in an appealing manner.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

from odin import xray
from odin.utils import odinparser

def main(input_file, output):
    
    shotset = xray.Shotset.load(input_file)
    I = shotset.intensity_profile()
    
    fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(8,3.5))
    fig.tight_layout()
    
    ax[0].plot(I[:,0], I[:,0], lw=2) # should call Shotset.intensity() here
    ax[0].set_xlabel(r'q / $\AA$')
    ax[0].set_ylabel(r'I(q)')
    
    ax[1].imshow(np.transpose(I), cmap=cm.jet, interpolation="nearest")
    ax[1].set_xlabel('x')
    ax[1].set_ylabel('y')
    
    plt.savefig(output, bbox_inches='tight')
    print "Saved: %s" % output
    
    return
    
    
if __name__ == '__main__':
    
    parser = odinparser('Plot intensity profile of a shotset.')
    
    parser.add_argument('-i', '--input', type=str, help='An hdf shotset file.')
    parser.add_argument('-o', '--output', default='intensity_plot.pdf',
                        help='Image file to write. Append .pdf, .png, .jpg, etc. Default: intensity_plot.pdf')

    args = parser.parse_args()
    
    main(args.input, args.output)

