#!/usr/bin/env python

"""
Display a shot in polar coordinates
"""

from odin import xray
from odin.utils import odinparser
from odin.plot import InteractiveImshow

import numpy as np
import matplotlib.pyplot as plt


def main(shotset_fn):
    
    ss = xray.Shotset.load(shotset_fn)
    q_values = np.arange(0.4, ss.detector.q_max, 0.01)
    r  = ss[0].to_rings(q_values)
    
    im = InteractiveImshow(r.polar_intensities[0,:,:].T)
    plt.xlabel(r'$\phi$ / Degrees')
    plt.ylabel(r'q / $\AA^{-1}$')
    
    plt.show()
    
    return


if __name__ == '__main__':
	
    parser = odinparser('Plot a sequential series of rings at a specific q-value.')
    parser.add_argument('shotset', help='An ODIN shot file to plot')
    args = parser.parse_args()
    
    main(args.shotset)
